### ISSUE TITLE
[FEATURE] Create DynamoDB-table with CDK

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#13]
**What user story is this feature related to?**
User Story #4 
User Story Title: As a user I want to track a habit by using the dod

**What does this feature entail?**
This will create and deploy a DynamoDB table for saving data sent from diffrent devices

**Describe a suggested implentation**
Create a DynamoDB table with CDK and deploy it

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create DynamoDB table with CDK
- [x] Check that it deploys and is functional
- [x] Create APIs for interracting with 
- [x] Check that APIs and DynamoDB interracts correctly

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Devices can send data to the new table

**Additional context**
