### ISSUE TITLE
[FEATURE] Basic firmware simulator setup

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#14]
**What user story is this feature related to?**
User Story # General
User Story Title: general 

**What does this feature entail?**
Create a software simulator of the habit tracker that behaves identical / similar to the actual habit tracker in specific areas, namely
sending and receiving data from AWS and to track habits or a subset of habits.

The simulator is there to function as a substitute for the firmware / physical device for the backend team, for purposes such as testing and general development.

**Describe a suggested implentation**
A python implementation using the keyboard and aws sdk v2 libraries are suggested here.
Use keypresses to simulate interaction with the dodecahedron / habit tracker. Specifically to emulate the process of selecting a side to track a habit.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create a class representing the physical device / firmware / habit tracker
- [x] Create functionality that emulates the interaction with the physical device, that is to select a specific side of the dodecahedron / habit tracker to start tracking a habit.
- [x] Implement a function that handles the sending of data to the AWS cloud using protocol buffers.

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The above task list is completed
