### ISSUE TITLE
[FEATURE] Set up API for configuring a device

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#15]
**What user story is this feature related to?**
User Story #6 
User Story Title: As a user i want to be able to add and remove tracked habits on each side of the device

**What does this feature entail?**
This will make the user able to send configurations for the device to the cloud

**Describe a suggested implentation**
Implement a REST API with both GET and PUT for interracting with a IoT core shadow for a given device

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create a shadow using the console
- [x] Create an HTTP API for interracting with the shadow
- [ ] Create a shadow using CDK (_optional_)
- [ ] Change the API to interract with the shadow created with CDK (_optional_)

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] The HTTP API can get the shadow
- [x] The HTTP API can update the shadow

**Additional context**
None given
