### ISSUE TITLE
[FEATURE] Add update function for posting new habitEvents

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#18]
**What user story is this feature related to?**
User Story #4 
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Adding a lambda function to habit-storage-stack for adding habit events to HabitTable. Make it be triggerable with both an HTTP API and IoT rule. The IoT rule should be able to use it with protobuff

**Describe a suggested implentation**
Copy existing function from dod-demo-function (in lambda) and add it to the lambda functions in hab it-storage-stack

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Add the lambda function  for updating HabitTable to habit-storage-stack
- [ ] Add IoT core rule for triggering the function
- [ ] Make it work with protobuff as input
- [ ] Make a seperate function for doing the same with an HTTP API
- [ ] Seperate all REST methods into seperate lambda functions _OPTIONAL_

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] It is possible to use the lambda function for updating the table
- [ ] It is possible to update the table using 
- [ ] It works with protobuff
- [ ] It works with the HTTP API

**Additional context**
Ask @EskildVeren  if you need help

**Comment by Mythois** [comment]
Outdated. Partially implemented already.
