### ISSUE TITLE
[FEATURE] Restructure database

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#19]
**What user story is this feature related to?**
User Story #7
User Story Title: As a user i want to be able to see a timeline of my tracked habits

**What does this feature entail?**
This will create a new database that is easier to get and update data

**Describe a suggested implentation**
Implement the following structure to the data. HabitEventTable and HabitTable are dynamoDB tables. habitEvent and habit are two diffrent types. partitionkeys are followed by [partitionkey]

**HabitEventTable**
UserId: number, [partitionkey]
habitId: number, [sortKey]
habitsEvents: habitEvents []

**HabitTable**
userId: number, [partitionkey]
habits: habit [] 

**habitEvent**
id: number
timestamp: number
value: number

**habit**
id: number [you can use timestamp]
habitName: string
type: string
deviceId: string

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Create another stack for habitevents named habit-event-storage
- [ ] Set up database matching the HabitEventTable-schema
- [ ] Update habitStorage to match the HabitTable-scema

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The tables have been seperated into two different stacks
- [ ] You can POST, GET and UPDATE data in both tables
- [ ] The README documentation for getting habits and habitevents are updated

**Additional context**
None provided
