### ISSUE TITLE
[FEATURE] Add API to let frontend get and create habits

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#20]
**What user story is this feature related to?**
User Story #6
User Story Title: As a user i want to be able to add and remove tracked habits on each side of the device

**What does this feature entail?**
This will give frontend the ability to let the user create a new habit that they want to track

**Describe a suggested implentation**
Update existing table for new databasestructure and create APIs using lambda and API gateway

Database structure under

HabitTable
userId: number, [partitionkey]
habits: habit []

habit
id: number
habitName: string
type: string
deviceId: string

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Talk to frontend about how they want this to be implemented
- [x] Update DynamoDB Table format
- [x] Create mock data for a user with 2 habits. His name is Fred
- [x] Add function for getting the habits of a user
- [x] Add function for creating new habits
- [ ] Pass this to frontend and see if it works

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] I can read my habits from frontend
- [ ] I can create new habits from frontend

**Additional context**
None given
