### ISSUE TITLE
[FEATURE] Implement backend resources for user registration and user login

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#27]
**What user story is this feature related to?**
User Story #2
User Story Title: As a user i want to be able to create a user and log in

**What does this feature entail?**
Implementing user registration and user login

**Describe a suggested implentation**
I dont have a suggested implementation

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Research AWS Cognito
- [ ] Come back and add more tasks
- [ ] Task 3

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] New users can be registered
- [ ] Existing users can log into their account
- [ ] Criteria 3

**Additional context**
