### ISSUE TITLE
[FEATURE] Create database for storing HabitEvents

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#34]
**What user story is this feature related to?**
User Story #4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Creating a database for storing HabitEvents and a HTTP API for getting the events out

**Describe a suggested implentation**
Look at the databasestructur in issue #19, and mimic one of the existing APIs from habit-storage

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Look at the databasestructur in issue #19,
- [ ] Create Lambdafunctions to add HabitEvents to the table
- [x] Create LambdaFunction for getting HabitEvents from the table
- [ ] Create HTTP API for gtriggering both lambdafunctions
- [ ] Create tests for this new function

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The database can store habitEvents
- [ ] You can get habitEvents out of the database
- [ ] e2e tests for getting habitEvents are created with httpiness
- [ ] unit tests for "final lambda code" are created

**Additional context**
