### ISSUE TITLE
[FEATURE] Make lambda function to store habit data in database

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#40]
**What user story is this feature related to?**
User Story 4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
The data sent to AWS from the habit tracker needs to be stored in a database. At the moment we can decode incomming messages, but they are not stored anywhere. This issue aims to address this. 

**Describe a suggested implentation**
Update mjs code in the lambda function which is currently called "storingHabitDataLambda". 

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Determin the habit type of the incomming message
- [ ] Store relevant data in the DB currently called "HabitEventTable"

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The tasks in the task list are completed

**Additional context**

**Comment by Mythois** [comment]
Duplicate issue with #48. Thus this issue will be closed. 
The feature has been implemented.
