### ISSUE TITLE
[FEATURE] Create index in HabitEventTable with deviceId

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#43]
**What user story is this feature related to?**
User Story #4
User Story Title: As a user I want to track a habit by using the device exclusively after configuration

**What does this feature entail?**
Create index in HabitEventTable for searching for deviceId. Will make writing to database from firmware much easier

**Describe a suggested implentation**
Can be done in console, but hould be done in code

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Try to create index
- [ ] Check if it appears in the console
- [ ] Test that you can use it to write to the database

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The database has an index for deviceId
- [ ] The index is usable

**Additional context**
