### ISSUE TITLE
[FEATURE] Add deviceside to response when getting habits

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#44]
**What user story is this feature related to?**
User Story #7
User Story Title: As a user i want to be able to see a timeline of my tracked habits

**What does this feature entail?**
Get side from deviceshadow when getting habits

**Describe a suggested implentation**
Get side from shadow and combine it with getHabits

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Manage to get shadow
- [ ] Combine devicesides with habitIds to get shadow
- [ ] Test

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] Correct deviceside is appended when getting a users habits

**Additional context**
