### ISSUE TITLE
[FEATURE] Update storingHabitDataLambda to store incomming habit event data in HabitEventTable

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#48]
**What user story is this feature related to?**
User Story: 6
User Story Title: As a user i want to be able to add and remove tracked habits on each side of the device

**What does this feature entail?**
Data sent by the habit tracker to AWS IoT needs to be stored in a database for later use. The lambda function 'storingHabitDataLambda' takes the decoded message (decoded by the TopicRule protocolBuffersToJSONRule) and stores it in the table 'HabitEventTable'. 

**Describe a suggested implentation**
Update the code of the lambda function to store the data.

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Get the decoded data 
- [ ] Get the table to store the data in
- [ ] Store the data
- [ ] Send success and / or error data to an MQTT topic

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The lambda function stores the data in the table
- [ ] The data is stored in the correct format
- [ ] Error and success messages are published to the 

**Additional context**
