### ISSUE TITLE
[FEATURE] Create an HTTP API for editing a users habits

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#50]
**What user story is this feature related to?**
User Story #6
User Story Title: As a user i want to be able to add and remove tracked habits on each side of the device

**What does this feature entail?**
Create an hTTP API for editing a users habits

**Describe a suggested implentation**
Create a lambda function for updating habits in UserDataTable, and hook it up to a HTTP endpoint

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Create lambda function for updating a list UserDataTable
- [ ] Connect the lambda funcion to an API-route
- [ ] Write tests and check that it works

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] Habits in the UserDataTable can be edited via a HTTP API

**Additional context**
