### ISSUE TITLE
[FEATURE] Create API for deleting habits from frontend

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#51]
**What user story is this feature related to?**
User Story #10
User Story Title: As a user I want to be able to delete my user data.

**What does this feature entail?**
This will involve createing an HTTP API for deleting habits from frontend

**Describe a suggested implentation**
Create HTTP API with lambda handlers for deleting a habit from UserDataTable. 

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Create API with enpoints and hook it up to a lambda function
- [ ] Create a lambdafunction for deleting habits from a user. Should probably not delete Frodes habits. Do not hurt my Frode
- [ ] Write e2e tests and unit tests for the API

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] There exists an API for deleting Habits from the habittable

**Additional context**
