### ISSUE TITLE
[FEATURE] Allow firmwareSimulator to receive updates

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#56]
**What user story is this feature related to?**
User Story #
User Story Title: 

**What does this feature entail?**
The habit tracker can eventually be updated so that each of its sides holds a different habit. This feature should also be present in the firmwareSimulator.

**Describe a suggested implentation**
Implement the subscription methods in the firmwareSimulator code properly so that the firmwareSimulator can subscribe to the required MQTT topics to receive its updates. Also, enable the firmwareSimulator to be able to decode the incomming protocol buffer messages representing the update. 

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Implement decode functionality for incomming protocol buffer messages
- [x] Implement functionality for updating sides

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] Introduces no new bugs
- [x] Implements this feature satisfactory 

**Additional context**
