### ISSUE TITLE
[FEATURE] Implement setup for FirmwareSimulator

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#64]
**What user story is this feature related to?**
User Story #
User Story Title: 

**What does this feature entail?**
Implements a setup process to automatically setup the FirmwareSimulator in AWS IoT for the user.
The setup will generate credentials, the AWS IoT thing representing the FirmwareSimulator, necessary policies providing required permissions and a thing / device shadow.

**Describe a suggested implentation**
Use boto3 library and python

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Create setup.py file
- [x] Create a config.py file that contains parameters / variables with values used accross the other FirmwareSimulator related files.

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] The setup file creates an AWS thing successfully
- [x] The setup creates a device shadow for the AWS thing successfully
- [x] The config.py file contains all the relevant parameters

**Additional context**

**Comment by Mythois** [comment]
See previous comment
