### ISSUE TITLE
[FEATURE] Create API for storing and getting habit goals

### ISSUE THREAD

**Issue by EskildVeren** [IT2901Nordic2024/backend#67]
**What user story is this feature related to?**
User Story #13/14
User Story Title: As a user I want to be able to set myself goals connected to my habit tracking / As a user I want to be able to view how my progress towards my goal

**What does this feature entail?**
Making the user able to set and see its habit goals

**Describe a suggested implentation**
Create an API and hook it up to a lambda functions that stores and gets habit goals

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Create lambda function for creating goals
- [ ] Create lambda funciton for getting goals
- [ ] Hook it up to the UserData api
- [ ] Test

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] Frontend can get habit goals for a user
- [ ] Frontend can set habit goals for a user

**Additional context**
