### ISSUE TITLE
[FEATURE] Update how FirmwareSimulator receives updates from AWS

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#69]
**What user story is this feature related to?**
User Story #
User Story Title: 

**What does this feature entail?**
The FirmwareSimulator should receive updates the same way as the habit tracker does.

**Describe a suggested implentation**
Update the update_sides method in FirmwareSimulator.py

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [ ] Remove config.proto and its python and desc files.
- [ ] Update the update_sides method

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [ ] The sides of the FirmwareSimulator update correctly
- [ ] No new bugs

**Additional context**
