### ISSUE TITLE
[FEATURE] Update FirmwareSimulator documentation

### ISSUE THREAD

**Issue by Mythois** [IT2901Nordic2024/backend#79]
**What user story is this feature related to?**
User Story #
User Story Title: 

**What does this feature entail?**
The FirmwareSimulator has progressed significantly. Consequently, the documentation needs to be updated, so that the simulator can be of use to potential users. 

**Describe a suggested implentation**
Update `README.md` in the firmwareSimulator folder.
Create a requirements.txt file using  `pip freeze > requirements.txt`

**Task list**
Describe small, specific tasks that have to be completed for this feature to be fulfilled. Make the list longer or shorter as needed.
- [x] Add an updated description of the FirmwareSimulator to the `README.md` file
- [x] Add a `requirements.txt` file showing all the python modules / libraries required.
- [x] Add a chapter describing how to use the FirmwareSimulator. The chapter should include a step-by-step description
- [x] (Optional) Add a guide on how to install the `AWS CLI`, which is required for using the FirmwareSimulator. 

**Acceptance criteria**
Describe specific criteria for this feature request to be fulfilled, for instance specific styling.
- [x] No new bugs are introduced
- [x] The `REAME.md` is easy to read
- [x] A person not part of the backend team should have looked at the `README.md` and deemed it useful

**Additional context**
